[build]
  publish = "."

[[redirects]]
  from = "/admin-login"
  to = "/admin-login.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/products"
  to = "/admin/products.html"
  status = 200

[[redirects]]
  from = "/admin/inventory"
  to = "/admin/inventory.html"
  status = 200

[[redirects]]
  from = "/admin/orders"
  to = "/admin/orders.html"
  status = 200

[[redirects]]
  from = "/admin/customers"
  to = "/admin/customers.html"
  status = 200

[[redirects]]
  from = "/admin/invoices"
  to = "/admin/invoices.html"
  status = 200

[[redirects]]
  from = "/admin/settings"
  to = "/admin/settings.html"
  status = 200

[[redirects]]
  from = "/products"
  to = "/products.html"
  status = 200

[[redirects]]
  from = "/product-detail"
  to = "/product-detail.html"
  status = 200

[[redirects]]
  from = "/checkout"
  to = "/checkout.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200
